import { ProjectItem } from './saasProjects';

export const projects: ProjectItem[] = [
  {
    title: 'AlwaysApply',
    type: 'Featured Project',
    description: 'Modern job portal for seekers and employers with search, filtering, and real-time notifications.',
    highlights: [
      'Dual-role auth for job seekers and employers',
      'Advanced search and personalized recommendations',
      'Application tracking and resume uploads',
    ],
    technologies: [
      'Next.js',
      'Firebase',
      'TypeScript',
      'Cloudinary',
      'Redux Toolkit',
    ],
    image: '/alwaysApply.png',
    code: 'https://github.com/prynskaf/job-portal.git',
    webkitURL: 'https://job-portal-eta-taupe.vercel.app/',
    role: 'Full Stack',
    status: 'Live',
    year: '2024',
  },
  {
    title: 'Shopper',
    type: 'Featured Project',
    description: 'Full-stack e-commerce app with product browsing, cart management, and Stripe checkout.',
    highlights: [
      'Sanity CMS for product management',
      'Clerk authentication',
      'Stripe-powered checkout flow',
    ],
    technologies: ['Next.js', 'TypeScript', 'Sanity', 'Clerk', 'Stripe'],
    image: '/shopper.png',
    code: 'https://github.com/prynskaf/shoppr',
    webkitURL: 'https://shopper-eta-five.vercel.app/',
    role: 'Full Stack',
    status: 'Live',
    year: '2024',
  },
  {
    title: 'SocialConnect',
    type: 'Featured Project',
    description: 'Social platform for posting updates and community engagement with secure authentication.',
    highlights: [
      'Posts and threaded comments',
      'MongoDB-backed user data',
      'React frontend with Express API',
    ],
    technologies: ['React', 'MongoDB', 'Express', 'TypeScript'],
    image: '/socialNew.png',
    code: 'https://github.com/prynskaf/SocialApp',
    webkitURL: 'https://social-app-silk-nine.vercel.app',
    role: 'Full Stack',
    status: 'Live',
    year: '2023',
  },
];
